# Numpy Fundamentals

### What is numpy?

1. **Core Object**: At its core, NumPy offers the `ndarray` object, which is a multi-dimensional array of homogeneous data types.
2. **Purpose**: It is designed for scientific computing and numerical operations on large data arrays.
3. **Functionality**:
   - **Mathematical Operations**: Includes support for basic mathematical operations like addition, subtraction, multiplication, and division.
   - **Linear Algebra**: Provides tools for basic linear algebra operations.
   - **Statistical Tools**: Offers functions for basic statistical operations such as mean, median, variance, etc.
   - **Fourier Transforms**: Includes capabilities to perform discrete Fourier transforms.
   - **Random Number Generation**: Supports generating random numbers for simulations.
4. **Performance**: Optimized for performance, utilizing internal optimizations and compiled code to accelerate operations.

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [7]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


In [5]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [12]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [19]:
# with reshape
np.arange(24).reshape(2, 4, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [26]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
# np.random
np.random.random((3,4))

array([[0.31413829, 0.63119596, 0.80252768, 0.08138368],
       [0.64982766, 0.13172394, 0.76413681, 0.43698619],
       [0.84719081, 0.18434997, 0.77863783, 0.96849128]])

In [30]:
# np.linspace
np.linspace(0,100,11,dtype=float)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [33]:
# np.linspace
np.linspace(0,100,10,dtype=float)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [32]:
# np.linspace
np.linspace(0,100,10,dtype=int)

array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100])

In [34]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
# np.identity
np.identity(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### Array Attributes

In [41]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(24).reshape(2,4,3)

In [43]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [44]:
# ndim
a3.ndim

3

In [45]:
# shape
print(a3.shape)
a3

(2, 4, 3)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [46]:
 # size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [47]:
# itemsize
a3.itemsize

8

In [48]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


In [49]:
a1.itemsize

4

### Changing Datatype

In [50]:
# astype
a3.astype(np.int32)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]], dtype=int32)

### Array Operations

In [51]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [52]:
""" scalar operations """

' scalar operations '

In [53]:
# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [56]:
# relational
a2 >= 15

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [58]:
""" vector operations """

' vector operations '

In [59]:
# arithmetic
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

### Array Functions

In [60]:
a1 = np.random.random((3,3))
print(a1)
a1 = np.round(a1*100)
a1

[[0.7604058  0.85441694 0.90868501]
 [0.11789567 0.11663732 0.93930357]
 [0.88822123 0.30362702 0.69673432]]


array([[76., 85., 91.],
       [12., 12., 94.],
       [89., 30., 70.]])

In [62]:
np.sum(a1), np.max(a1), np.min(a1), np.mean(a1)

(559.0, 94.0, 12.0, 62.111111111111114)

In [63]:
# max/min/sum/prod
# 0 -> col and 1 -> row

In [67]:
np.max(a1, axis=0),np.min(a1, axis=0)

(array([89., 85., 94.]), array([12., 12., 70.]))

In [68]:
np.max(a1, axis=1),np.min(a1, axis=1)

(array([91., 94., 89.]), array([76., 12., 30.]))

In [69]:
np.prod(a1,axis=0)

array([ 81168.,  30600., 598780.])

In [70]:
np.mean(a1)

62.111111111111114

In [72]:
# mean/median/std/var
np.var(a1,axis=1)

array([  38.        , 1494.22222222,  604.66666667])

In [71]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.56610764, -0.17607562,  0.10598751],
       [-0.53657292, -0.53657292, -0.24525199],
       [ 0.86006941, -0.98803162,  0.77389068]])

In [73]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [75]:
# log and exponents
np.exp(a1), np.log(a1)

(array([[1.01480039e+33, 8.22301271e+36, 3.31740010e+39],
        [1.62754791e+05, 1.62754791e+05, 6.66317622e+40],
        [4.48961282e+38, 1.06864746e+13, 2.51543867e+30]]),
 array([[4.33073334, 4.44265126, 4.51085951],
        [2.48490665, 2.48490665, 4.54329478],
        [4.48863637, 3.40119738, 4.24849524]]))

In [76]:
# round/floor/ceil
mat = np.random.random((2,3))*100
mat, np.ceil(mat), np.floor(mat), np.round(mat)

(array([[ 9.8551977 , 85.89948508, 21.14965802],
        [67.60821418, 93.31498723, 67.53235069]]),
 array([[10., 86., 22.],
        [68., 94., 68.]]),
 array([[ 9., 85., 21.],
        [67., 93., 67.]]),
 array([[10., 86., 21.],
        [68., 93., 68.]]))

### Indexing and Slicing

In [116]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(60).reshape(3,4,5)

a1, a2, a3

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],
 
        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],
 
        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]]))

In [80]:
a1[0], a1[-1]

(0, 9)

In [87]:
a2[1][1], a2[1][-3], a2[-2][-3], a2[1, 1], a2[1, -3], a2[-2, -3]

(5, 5, 5, 5, 5, 5)

In [88]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [92]:
a3[0, 2, 1], a3[0][2][1]

(7, 7)

In [94]:
a3[0,0,0], a3[-2, -4, -3]

(0, 0)

In [96]:
a1, a1[2:5], a1[2:5:2]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([2, 3, 4]), array([2, 4]))

In [99]:
a2, a2[0, :], a2[:, 2]

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([0, 1, 2, 3]),
 array([ 2,  6, 10]))

In [100]:
a2[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [105]:
# All four corner elements of a2
a2[0::2, 0::3]
a2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [106]:
a2[0::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [107]:
a2[1, 0::3]

array([4, 7])

In [119]:
a3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [117]:
a3[1]

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [118]:
a3[0::2]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [120]:
a3[0, 1]

array([5, 6, 7, 8, 9])

In [121]:
a3[1, :, 2]

array([22, 27, 32, 37])

In [123]:
a3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [124]:
a3[2, 2:, 3:]

array([[53, 54],
       [58, 59]])

In [125]:
a3[0::2, 0, 0::4]

array([[ 0,  4],
       [40, 44]])

### Iterating

In [127]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
for val in a1:
  print(val, end=" ")

0 1 2 3 4 5 6 7 8 9 

In [133]:
a2, a2.ndim, a2.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 2,
 (3, 4))

In [134]:
for val in a2:
    print(val)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [135]:
a3, a3.ndim, a3.shape

(array([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],
 
        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],
 
        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]]),
 3,
 (3, 4, 5))

In [136]:
for val in a3:
  print(val)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
[[40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


In [138]:
for i in np.nditer(a3):
  print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 

### Reshaping

In [142]:
""" reshape operations """

' reshape operations '

In [141]:
# Transpose
for elem in [a2, np.transpose(a2), a2.T]:
    print(elem, end="\n\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]



In [144]:
# ravel
for elem in [a2, a2.ravel()]:
    print(elem, end="\n\n")
for elem in [a3, a3.ravel()]:
    print(elem, end="\n\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]



### Stacking

In [147]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
for element in [a4, a5]:
    print(element, element.ndim, element.shape, end="\n\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2 (3, 4)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 2 (3, 4)



In [148]:
# Horizozntal Stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [149]:
# Vertical Stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [151]:
# horizontal splitting
a6 = np.hstack((a4,a5))
a6

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [153]:
np.hsplit(a6,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [154]:
np.hsplit(a6,3)

ValueError: array split does not result in an equal division

In [ ]:
# vertical splitting

In [156]:
a7 = np.vstack((a4,a5))
a7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [157]:
np.vsplit(a7,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [158]:
np.vsplit(a7,3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [159]:
np.vsplit(a7,4)

ValueError: array split does not result in an equal division